apiVersion: apps/v1
kind: Deployment
metadata:
  name: podset-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: podset-operator
  template:
    metadata:
      labels:
        name: podset-operator
    spec:
      serviceAccountName: podset-operator
      containers:
        - name: podset-operator
          # Replace this with the built image name
          image: docker.io/mariolet/podset-operator@sha256:94e5e0dc30f159b0b7a04a2ad4ed063910093a692d20b4795cc4d9020667e020
          command:
          - podset-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "podset-operator"
